### ISSUE TITLE
Axios error with newest version

### ISSUE THREAD

**Issue by ui-mattlucas** [crowdin/ota-client-js#64] opened 2023-10-12 19:28 UTC
```
ERROR
Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at new AxiosHttpClient (http://localhost:3000/static/js/bundle.js:632:34)
    at new OtaClient (http://localhost:3000/static/js/bundle.js:395:94)
    at dynamicActivate (http://localhost:3000/static/js/bundle.js:242:18)
    at http://localhost:3000/static/js/bundle.js:251:5
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:28309:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:29802:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:29774:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:29764:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:29754:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:31639:7)
ERROR
Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at new AxiosHttpClient (http://localhost:3000/static/js/bundle.js:632:34)
    at new OtaClient (http://localhost:3000/static/js/bundle.js:395:94)
    at dynamicActivate (http://localhost:3000/static/js/bundle.js:242:18)
    at http://localhost:3000/static/js/bundle.js:251:5
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:28309:30)
    at invokePassiveEffectMountInDEV (http://localhost:3000/static/js/bundle.js:29998:17)
    at invokeEffectsInDev (http://localhost:3000/static/js/bundle.js:31897:15)
    at commitDoubleInvokeEffectsInDEV (http://localhost:3000/static/js/bundle.js:31880:11)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:31653:9)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:31591:18)
```

We were following the basic tutorial to test Lingui and got this error. 

By pinning the version of the Ota-client to 0.7 everything works properly. 

```
export async function dynamicActivate(locale) {
  const client = new otaClient(crowdinDistributionKey)
  // error is here ^
  const messages = await client.getStringsByLocale(locale)

  i18n.load(locale, messages)
  i18n.activate(locale)
}
```

Perhaps Axios could be updated from the version in the library?
Or maybe I did something wrong?

**Comment by andrii-bodnar** [comment] 2023-10-13 06:33
@ui-mattlucas I've already updated Axios in the `main` branch (#60). Do you think it will help to resolve the issue?

**Comment by andrii-bodnar** [comment] 2023-10-13 11:37
@ui-mattlucas I just released a new version - https://github.com/crowdin/ota-client-js/releases/tag/1.1.0

**Comment by TanSaalik** [comment] 2023-11-15 13:35
Having the same error with 1.1.1 as well. Also tried 1.1.0 and 1.0.0 - no luck. The error disappears when I install axios package separately and pass it in via config `httpClient` - but in that case I was getting errors about content object being null and not receiving any actual values.
And just like @ui-mattlucas - when I tried 0.7.0, it works just fine.

**Comment by andrii-bodnar** [comment] 2023-11-15 13:37
Hi @TanSaalik, could you please provide a [Minimal, Reproducible Example
](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you!

**Comment by TanSaalik** [comment] 2023-11-15 15:00
Let me try.
The app itslf is initiated with Create React App. (`"react": "^18.2.0",`)

### Working:
`"@crowdin/ota-client": "0.7.0"`

**App.js**
```
...
import otaClient from '@crowdin/ota-client';

const client = new otaClient(hash);

client.getStrings()
  .then(res => {
    console.log(res);
  })
  .catch(error => console.error(error));
...
```
and it logs the results nicely.

### Not working:
`"@crowdin/ota-client": "0.7.0"`

**App.js** - **identical** to the example above and getting:
```
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at new AxiosHttpClient (http://localhost:3000/static/js/bundle.js:2430:34)
    at new OtaClient (http://localhost:3000/static/js/bundle.js:2193:94)
    at ./src/App.js (http://localhost:3000/static/js/bundle.js:72:16)
...
```
where `at ./src/App.js` is pointing at `const client = new otaClient(hash);` 
and `at new AxiosHttpClient` is pointing at `class AxiosHttpClient {
  constructor() {
    this.axios = axios_1.default.create({});
  }`
If I install axios separately and pass the it as config in `App.js` (leaving everything else the same)
```
const config = {
  httpClient: axios,
};
const client = new otaClient(hash, config);
```
, then the error disappears, but is replaced by:
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at OtaClient.getJsonFiles (index.js:233:1)
    at async OtaClient.getStrings (index.js:143:1)
```
And resulting in no values received. Same for other functions like `getContent()` etc.
So not much to it and I hope it helps.

**Comment by andrii-bodnar** [comment] 2023-11-15 15:08
@TanSaalik perfect, thanks a lot for the details provided!

**Comment by yevheniyJ** [comment] 2023-11-19 15:15
@TanSaalik  @andrii-bodnar Thanks for raising this issue again.

After some investigations and playing with multiple different options I don't have an ideal fix for this but a workaround (for now):

```ts
import otaClient from '@crowdin/ota-client';

const client = new otaClient(hash, {
  httpClient: {
    get: async (url) => {
      const res = await axios.get(url);
      return res.data;
    }
  }
});
```

The thing is that it all works fine if either you use React Scripts 4.x version (current one 5.x) OR axios up to 1.1.0.  
Problem might be in Webpack 5 that React Scripts uses under the hood (also all works fine with default webpack 5 setup) or axios does not provide the correct output (might be a cause since there are few similar issues registered for axios). 

Also I tried with other "starters" that React describes here https://react.dev/learn/start-a-new-react-project and faced same issue only for [Expo](https://react.dev/learn/start-a-new-react-project#expo).

**Closed** 2023-11-20 10:21 UTC
Labels: bug, help wanted
